### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by cooler333** [opencv/opencv_for_ios_book_samples#5]
faceAnimator = new FaceAnimator(parameters);

../Chapter15_DetectingFacialFeatures/Chapter15_DetectingFacialFeatures/ViewController.m:160:18: No viable overloaded '='

can't set faceAnimator

**Comment by pradeepktg** [comment]
I get the same error

**Comment by cooler333** [comment]
@pradeepktg change "cv::Ptr<FaceAnimator> faceAnimator;" to "FaceAnimator *faceAnimator;"

but I do not know about the consequences

**Comment by pradeepktg** [comment]
@cooler333 Thank you. It works :) Do you how to detect facial expression/emotion recognition ?
